# Generated by Django 4.2 on 2024-09-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="urlcontent",
            name="title",
            field=models.TextField(default="title"),
            preserve_default=False,
        ),
    ]
