# Generated by Django 4.2 on 2024-09-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_urlcontent"),
    ]

    operations = [
        migrations.AddField(
            model_name="urlcontent",
            name="summery",
            field=models.TextField(default="aaa"),
            preserve_default=False,
        ),
    ]
