# Generated by Django 4.2 on 2024-09-13 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_rename_article_comment_post_comment_author_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="post",
        ),
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
        migrations.RemoveField(
            model_name="post",
            name="like_count",
        ),
    ]
