# Generated by Django 4.2 on 2024-09-17 09:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_birthday_user_gender_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="followings",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
